### ISSUE TITLE
why not implememt the interface ? 

### ISSUE THREAD

**Issue by championswimmer** [duxinxiao/boss-ts-template#1]
https://github.com/duxinxiao/boss-ts-template/blob/2855ffa1220ec629742ac320b32ba111c7a0a76a/src/store/modules/user.ts#L14

why not 
```ts
class Stuff extends VuexModule implements IStuff {}
```

**Comment by duxinxiao** [comment]
wow, thanks for notifying ( BTW, love your library

**Comment by championswimmer** [comment]
Thank you so much.
If you ever have any feedback, do feel free to create an issue on the library :) 

Love to see you using it!
